name: "deno test"
on:
  issue_comment:
    types: [created]
    
jobs:
  denotest:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.4
      - run: |
          deno --version
          deno run --allow-net https://deno.land/x/distancecalculator/test-it.ts
